# Generated by Django 5.0.7 on 2024-08-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('nationality_id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_symbol', models.CharField(max_length=50)),
                ('rank_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('trait_id', models.AutoField(primary_key=True, serialize=False)),
                ('trait_name', models.CharField(max_length=100)),
                ('trait_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('personal_link', models.URLField(blank=True, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('languages', models.ManyToManyField(blank=True, to='coworkers.language')),
                ('nationalities', models.ManyToManyField(blank=True, to='coworkers.nationality')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coworkers.rank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationExperience',
            fields=[
                ('education_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('study_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('certificate', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_measure', models.PositiveIntegerField()),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworkers.trait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'trait')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='traits',
            field=models.ManyToManyField(blank=True, through='coworkers.WorkerTrait', to='coworkers.trait'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('job_position', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
