# Generated by Django 5.1.2 on 2024-11-12 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkers', '0006_rename_email_address_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_knowledge', models.CharField(choices=[('Beginner', 'Beginner'), ('Professional', 'Professional'), ('Native', 'Native')], max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworkers.trait')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'language')},
            },
        ),
    ]
