# Generated by Django 5.1.2 on 2024-11-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkers', '0007_workerlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworkers.language'),
        ),
    ]
