# Generated by Django 5.1.4 on 2024-12-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkers', '0010_customuser_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='This person is a eager talented worker that is seeking for a position at multiple potential companies. He has not indicated any work experience records, but still can successfully do his job.'),
        ),
    ]
